"""Карточки-квиз."""
from __future__ import annotations

from . import Flashcard

FLASHCARDS: tuple[Flashcard, ...] = (
    Flashcard(
        id="fc-print-sep",
        section_id="00-intro",
        question="Что выведет print(\"a\", \"b\", sep=\"-\")?",
        options=("a-b", "a b", "a,b", "ab"),
        correct_index=0,
        explanation_md="`sep` задаёт разделитель между аргументами `print`. По умолчанию — пробел, мы поменяли на `-`.",
    ),
    Flashcard(
        id="fc-comment",
        section_id="00-intro",
        question="Какой символ начинает однострочный комментарий в Python?",
        options=("//", "#", "--", "/*"),
        correct_index=1,
        explanation_md="`#` и всё до конца строки — это комментарий. Python его игнорирует.",
    ),
    Flashcard(
        id="fc-input-type",
        section_id="01-vars",
        question="Что возвращает функция input()?",
        options=("число (int)", "строку (str)", "True или False", "ничего (None)"),
        correct_index=1,
        explanation_md="Всегда строку. Если нужно число — оборачивай: `int(input(...))`.",
    ),
    Flashcard(
        id="fc-int-cast",
        section_id="01-vars",
        question="Что выведет int(\"42\") + 1?",
        options=("\"43\"", "43", "ошибку", "421"),
        correct_index=1,
        explanation_md="`int(\"42\")` превращает строку в число, а потом обычное сложение.",
    ),
    Flashcard(
        id="fc-fstring",
        section_id="01-vars",
        question="Какая запись правильная для подстановки имени name?",
        options=(
            "\"Привет, {name}!\"",
            "f\"Привет, {name}!\"",
            "f\"Привет, $name!\"",
            "\"Привет, $name!\"",
        ),
        correct_index=1,
        explanation_md="f-строка — обязателен префикс `f` перед открывающей кавычкой.",
    ),
    Flashcard(
        id="fc-eq-vs-eqeq",
        section_id="02-cond",
        question="Чем отличается = от ==?",
        options=(
            "Ничем",
            "= присваивает значение, == сравнивает",
            "== присваивает значение, = сравнивает",
            "= это для чисел, == это для строк",
        ),
        correct_index=1,
        explanation_md="`=` записывает значение в переменную. `==` сравнивает два значения и даёт `True`/`False`.",
    ),
    Flashcard(
        id="fc-elif",
        section_id="02-cond",
        question="Что делает elif в цепочке?",
        options=(
            "Останавливает выполнение",
            "«Иначе если»: следующая проверка, если предыдущая дала False",
            "Создаёт новую переменную",
            "Это синоним else",
        ),
        correct_index=1,
        explanation_md="`elif` — следующая ветка, проверяется только если все предыдущие условия не прошли.",
    ),
    Flashcard(
        id="fc-and",
        section_id="02-cond",
        question="Когда True and False даёт True?",
        options=("Никогда", "Всегда", "Только в Python 3", "Зависит от версии"),
        correct_index=0,
        explanation_md="`and` истинно только когда **оба** значения истинны.",
    ),
    Flashcard(
        id="fc-list-index",
        section_id="03-collections",
        question="С какого индекса начинаются элементы списка?",
        options=("С 0", "С 1", "С -1", "Зависит от длины"),
        correct_index=0,
        explanation_md="В Python (и в большинстве языков) индексы списков идут **с 0**.",
    ),
    Flashcard(
        id="fc-list-last",
        section_id="03-collections",
        question="Как получить последний элемент списка lst?",
        options=("lst[len(lst)]", "lst[-1]", "lst.last()", "lst[end]"),
        correct_index=1,
        explanation_md="Отрицательные индексы идут с конца. `lst[-1]` — последний элемент.",
    ),
    Flashcard(
        id="fc-dict-access",
        section_id="03-collections",
        question="Как взять значение по ключу name из словаря d?",
        options=("d.name", "d[\"name\"]", "d->name", "d.get_name()"),
        correct_index=1,
        explanation_md="`d[\"name\"]` — стандартный доступ. Если ключа может не быть — `d.get(\"name\")`.",
    ),
    Flashcard(
        id="fc-range-end",
        section_id="04-loops",
        question="Что выведет for i in range(3): print(i)?",
        options=("1 2 3", "0 1 2", "0 1 2 3", "1 2"),
        correct_index=1,
        explanation_md="`range(n)` даёт числа от 0 до n-1 включительно. Конец **не входит**.",
    ),
    Flashcard(
        id="fc-while-when",
        section_id="04-loops",
        question="Когда лучше использовать while вместо for?",
        options=(
            "Никогда, for всегда лучше",
            "Когда заранее знаешь длину",
            "Когда не знаешь, сколько итераций будет — например, ждёшь правильный ввод",
            "Только для бесконечных циклов",
        ),
        correct_index=2,
        explanation_md="for — когда понятно, **по чему** идти. while — когда выход определяется условием, например пользователь ввёл правильный ответ.",
    ),
    Flashcard(
        id="fc-return-vs-print",
        section_id="05-funcs",
        question="В чём разница между return и print?",
        options=(
            "Это синонимы",
            "print выводит на экран, return возвращает значение в код",
            "return — для чисел, print — для строк",
            "return работает только в классах",
        ),
        correct_index=1,
        explanation_md="`print` показывает пользователю. `return` отдаёт значение коду, который вызвал функцию.",
    ),
    Flashcard(
        id="fc-args",
        section_id="05-funcs",
        question="Что означает *args в определении функции?",
        options=(
            "Указатель в стиле C",
            "Все позиционные аргументы соберутся в кортеж",
            "Все именованные аргументы соберутся в словарь",
            "Это синтаксическая ошибка",
        ),
        correct_index=1,
        explanation_md="`*args` — позиционные → кортеж. `**kwargs` — именованные → словарь.",
    ),
    Flashcard(
        id="fc-import",
        section_id="06-files",
        question="Как использовать функцию sqrt из модуля math?",
        options=(
            "use math::sqrt",
            "import math; math.sqrt(9)",
            "include math; sqrt(9)",
            "math.import().sqrt(9)",
        ),
        correct_index=1,
        explanation_md="Сначала `import math`, потом `math.sqrt(9)`. Или `from math import sqrt` — тогда просто `sqrt(9)`.",
    ),
    Flashcard(
        id="fc-with-open",
        section_id="06-files",
        question="Зачем использовать with при работе с файлом?",
        options=(
            "Это просто красивее",
            "with гарантирует, что файл будет закрыт даже при ошибке",
            "with быстрее обычного open",
            "with нужен только в Windows",
        ),
        correct_index=1,
        explanation_md="`with` автоматически закрывает файл при выходе из блока — даже если внутри произошла ошибка.",
    ),
    Flashcard(
        id="fc-pip",
        section_id="07-pip-api",
        question="Зачем создавать виртуальное окружение (venv)?",
        options=(
            "Чтобы Python работал быстрее",
            "Чтобы у каждого проекта были свои версии библиотек",
            "Чтобы скрыть код",
            "venv — это синоним requirements.txt",
        ),
        correct_index=1,
        explanation_md="venv изолирует зависимости одного проекта от системных и других проектов — никаких конфликтов версий.",
    ),
    Flashcard(
        id="fc-json",
        section_id="06-files",
        question="Что делает json.dumps(data)?",
        options=(
            "Скачивает JSON по URL",
            "Превращает Python-объект (словарь, список) в строку JSON",
            "Превращает строку JSON в Python-объект",
            "Пишет JSON в файл",
        ),
        correct_index=1,
        explanation_md="`json.dumps` (dump-string) — Python → строка JSON. Обратное — `json.loads` (load-string).",
    ),
    Flashcard(
        id="fc-bot-token",
        section_id="08-bot",
        question="Где безопасно хранить токен Telegram-бота?",
        options=(
            "В файле bot.py прямо в коде, который заливается в публичный репо",
            "В переменной окружения / .env-файле, не зашитом в репо",
            "В комментариях кода",
            "В картинке аватарки",
        ),
        correct_index=1,
        explanation_md="Токен — это пароль. Никогда не клади его в публичный код. Стандарт — переменная окружения или `.env`.",
    ),
)
